/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Vienji
 */
public class Load1 extends javax.swing.JFrame implements LoadListener{
    private String sample;
    /**
     * Creates new form Load1
     */
    public Load1() {
        initComponents(); 
    }
    
     public Load1(String sample) {
        initComponents(); 

        System.out.println(sample);
        this.sample = sample;
        load();
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadingBar = new javax.swing.JProgressBar();
        loadingModule = new javax.swing.JLabel();
        loadingValue = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        enter = new javax.swing.JButton();
        change = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        loadingModule.setText("Loading...");

        loadingValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        loadingValue.setText("0%");

        welcome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        welcome.setText("Welcome");

        enter.setText("Enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        change.setText("Change");
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loadingBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(loadingModule)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loadingValue))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(welcome))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(enter, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 140, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(change)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(change)
                .addGap(28, 28, 28)
                .addComponent(welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadingValue)
                    .addComponent(loadingModule))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loadingBar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(enter)
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed

        Load2 load2 = new Load2();
        load2.a();
        
        loadingBar.setValue(20);
        loadingModule.setText("A");
        loadingValue.setText(String.valueOf(20) + "%");
        
        System.out.print("A");
        
        load2.b();
        
        loadingBar.setValue(40);
        loadingModule.setText("B");
        loadingValue.setText(String.valueOf(40) + "%");
        
        System.out.print("B");
        load2.c();
        
        loadingBar.setValue(60);
        loadingModule.setText("C");
        loadingValue.setText(String.valueOf(60) + "%");
        
        System.out.print("C");
        load2.d();
        loadingBar.setValue(80);
        loadingModule.setText("D");
        loadingValue.setText(String.valueOf(80) + "%");
        System.out.print("D");
        load2.e();
        loadingBar.setValue(100);
        loadingModule.setText("E");
        loadingValue.setText(String.valueOf(100) + "%");
        System.out.print("E");
        load2.setVisible(true);

    }//GEN-LAST:event_enterActionPerformed

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        welcome.setText("Sample");
        Load2 load2 = new Load2();
        load2.a();
        
        loadingBar.setValue(20);
        loadingModule.setText("A");
        loadingValue.setText(String.valueOf(20) + "%");
        
        System.out.print("A");
        
        load2.b();
        
        loadingBar.setValue(40);
        loadingModule.setText("B");
        loadingValue.setText(String.valueOf(40) + "%");
        
        System.out.print("B");
        load2.c();
        
        loadingBar.setValue(60);
        loadingModule.setText("C");
        loadingValue.setText(String.valueOf(60) + "%");
        
        System.out.print("C");
        load2.d();
        loadingBar.setValue(80);
        loadingModule.setText("D");
        loadingValue.setText(String.valueOf(80) + "%");
        System.out.print("D");
        load2.e();
        loadingBar.setValue(100);
        loadingModule.setText("E");
        loadingValue.setText(String.valueOf(100) + "%");
        System.out.print("E");
        load2.setVisible(true);

    }//GEN-LAST:event_changeActionPerformed

    private void a(){
        try{
            for(int i = 0; i <= 100; i++){
                Thread.sleep(50);
            }
        } catch(Exception e){}
    }
    
    private void b(){
        try{
            for(int i = 0; i <= 100; i++){
                Thread.sleep(50);
            }
        } catch(Exception e){}
    }
    
    private void c(){
        try{
            for(int i = 0; i <= 100; i++){
                Thread.sleep(50);
            }
        } catch(Exception e){}
    }
    
    private void d(){
        try{
            for(int i = 0; i <= 100; i++){
                Thread.sleep(50);
            }
        } catch(Exception e){}
    }
    
    private void e(){
        try{
            for(int i = 0; i <= 100; i++){
                Thread.sleep(50);
            }
        } catch(Exception e){}
    }
    
    private void load(){
        Load2 load2 = new Load2(this,sample);
        load2.a();
        
        loadingBar.setValue(20);
         loadingModule.setText("A");
         loadingValue.setText(String.valueOf(20) + "%");
        
        System.out.print("A");
        
        load2.b();
        
         loadingBar.setValue(40);
         loadingModule.setText("B");
         loadingValue.setText(String.valueOf(40) + "%");
        
        System.out.print("B");
        load2.c();
         loadingBar.setValue(60);
         loadingModule.setText("C");
         loadingValue.setText(String.valueOf(60) + "%");
        
        System.out.print("C");
        load2.d();
         loadingBar.setValue(80);
         loadingModule.setText("D");
         loadingValue.setText(String.valueOf(80) + "%");
        System.out.print("D");
        load2.e();
         loadingBar.setValue(100);
         loadingModule.setText("E");
         loadingValue.setText(String.valueOf(100) + "%");
        System.out.print("E");
        load2.setVisible(true);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Load1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Load1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Load1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Load1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  
        
        /* Create and display the form */
        //Load1 l1 = new Load1();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new Load1().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton change;
    private javax.swing.JButton enter;
    private static javax.swing.JProgressBar loadingBar;
    private static javax.swing.JLabel loadingModule;
    private static javax.swing.JLabel loadingValue;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables

    @Override
    public void disposeLoadingScreen() {
        dispose();
    }

    @Override
    public void updateLoadingBar(int i) {
        loadingBar.setValue(i);
    }

    @Override
    public void updateLoadingModule(String module) {
        loadingModule.setText(module);
    }

    @Override
    public void updateLoadingPercentage(int i) {
        loadingValue.setText(String.valueOf(i) + "%");
    }
}
